---
# manual_metadata
# Please find the BIDS specification here:
# https://bids-specification--1128.org.readthedocs.build/en/1128/modality-specific-files/eye-tracking.html
# Please go through the specification
# and fill the fields below according to the data types given in the specification.
# !Note that ScreenSize and EyeTrackerDistance units are in meter, not centimeter!

# REQUIRED, fill according to BIDS specification (!the converter will not run successfully if you leave this empty!):
SampleCoordinateUnits: str
SampleCoordinateSystem: str
EnvironmentCoordinates: str
ScreenDistance: float # or express as X,Y,Z coordinates, e.g. [0.05, 0.30, 0.40]
ScreenRefreshRate: int
ScreenSize: [float]

# Recommended (leave empty if not available but put information you want to share with your dataset here!):
SoftwareVersion: str
ScreenAOIDefinition: [str, [int]]
EyeCameraSettings:
EyeTrackerDistance: float # or express as X,Y,Z coordinates, e.g. [0.05, 0.30, 0.40]
FeatureDetectionSettings:
GazeMappingSettings:
RawDataFilters:
InstitutionName: str
InstitutionAddress: str
TaskName: str
