---
# manual_metadata
# Please find the BIDS specification here:
# https://bids-specification--1128.org.readthedocs.build/en/1128/modality-specific-files/eye-tracking.html
# Please go through the specification
# and fill the fields below according to the data types given in the specification.
# !Note that ScreenSize and EyeTrackerDistance units are in meter, not centimeter!

# REQUIRED, fill according to BIDS specification (!the converter will not run successfully if you leave this empty!):
SampleCoordinateSystem: str
ScreenOrigin: [str, str]
Units: str

# Recommended or optional (leave empty if not available but put information you want to share with your dataset here!):
CalibrationPosition: [[int, int]]
SoftwareVersion: str
ScreenRefreshRate: int
ScreenSize: [float]
ScreenAOIDefinition: [str, [int]]
EyeCameraSettings:
ScreenDistance: float # or express as X,Y,Z coordinates, e.g. [0.05, 0.30, 0.40]
EyeTrackerDistance: float # or express as X,Y,Z coordinates, e.g. [0.05, 0.30, 0.40]
FeatureDetectionSettings:
GazeMappingSettings:
RawDataFilters: str
InstitutionName: str
InstitutionAddress: str
TaskName: str
