---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile, black]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--config, pyproject.toml]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies: [tomli]

-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        args: [--config-file=pyproject.toml]

-   repo: https://github.com/pyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [--config, .flake8, --verbose]
        additional_dependencies: [flake8-docstrings, flake8-use-fstring]
