# Generated by Neurodocker and Reproenv.

FROM ubuntu:22.04
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  ca-certificates \
                  curl \
                  gcc \
                  gnupg2 \
                  software-properties-common \
           && rm -rf /var/lib/apt/lists/*
RUN apt-key adv --fetch-keys https://apt.sr-research.com/SRResearch_key && add-apt-repository 'deb [arch=amd64] https://apt.sr-research.com SRResearch main'
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  eyelink-display-software \
           && rm -rf /var/lib/apt/lists/*

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "ubuntu:22.04" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "gnupg2", \
          "curl", \
          "gcc", \
          "ca-certificates", \
          "software-properties-common" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           ca-certificates \\\\\\n           curl \\\\\\n           gcc \\\\\\n           gnupg2 \\\\\\n           software-properties-common \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-key adv --fetch-keys https://apt.sr-research.com/SRResearch_key && add-apt-repository '"'"'deb [arch=amd64] https://apt.sr-research.com SRResearch main'"'"'" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "eyelink-display-software" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           eyelink-display-software \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    } \
  ] \
}' > /.reproenv.json
# End saving to specification to JSON.
