---
name: docker

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: [main]
    pull_request:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Clone
            uses: actions/checkout@v3
        -   name: Build docker image
            run: docker build -t eye2bids:latest .
